import { useContext, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../context/AuthContext";
import { request } from "../services/api";

export default function AuthForm({ mode }) { const signup = mode === "signup"; const [form, setForm] = useState({ name: "", email: "", password: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const { login } = useContext(AuthContext); const navigate = useNavigate();
  const submit = async (e) => { e.preventDefault(); setError(""); setLoading(true); try { const user = await request(`/auth/${signup ? "register" : "login"}`, { method: "POST", body: JSON.stringify(signup ? form : { email: form.email, password: form.password }) }); login(user); navigate("/products"); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <section className="auth-page"><form className="auth-card" onSubmit={submit}><p className="eyebrow">WELCOME TO SHOPNEST</p><h1>{signup ? "Create your account" : "Welcome back"}</h1><p>{signup ? "Create an account to place and track orders." : "Sign in to see your orders and check out."}</p>{error && <p className="notice error">{error}</p>}{signup && <label>Full name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/></label>}<label>Email address<input type="email" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })}/></label><label>Password<input type="password" minLength="6" required value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/></label><button className="button full" disabled={loading}>{loading ? "Please wait…" : signup ? "Create account" : "Log in"}</button><p className="form-switch">{signup ? "Already have an account?" : "New to ShopNest?"} <Link to={signup ? "/login" : "/signup"}>{signup ? "Log in" : "Sign up"}</Link></p></form></section>;
}
